# Generated by Django 3.2.2 on 2022-03-24 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8, verbose_name='Наименование (кратко)')),
            ],
            options={
                'verbose_name': 'Измерение',
                'verbose_name_plural': 'Измерения',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления в БД')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения в БД')),
                ('title', models.CharField(max_length=128, verbose_name='Наименование')),
                ('desc', models.CharField(max_length=512, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления в БД')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения в БД')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Код')),
                ('comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='Комментарий')),
                ('date_start', models.DateField(verbose_name='Дата начала действия')),
                ('date_end', models.DateField(verbose_name='Дата конца действия')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления в БД')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения в БД')),
                ('comment', models.CharField(blank=True, max_length=512, null=True, verbose_name='Комментарий')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Сумма')),
                ('meas', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='delivery.measure', verbose_name='В чем измеряется')),
                ('promo', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.promo', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления в БД')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения в БД')),
                ('offers', models.ManyToManyField(to='delivery.Offer', verbose_name='Товары')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='В чем измеряется')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
