# Generated by Django 3.2.2 on 2022-03-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meas',
        ),
        migrations.AddField(
            model_name='offer',
            name='meas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='delivery.measure', verbose_name='В чем измеряется'),
        ),
    ]
