# Generated by Django 3.2.2 on 2022-03-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20220324_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='title_short',
            field=models.CharField(default='л', max_length=8, verbose_name='Наименование (кратко)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measure',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Наименование'),
        ),
    ]
