# Generated by Django 4.0.3 on 2022-04-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_address_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Общая сумма корзины'),
        ),
    ]
