# Generated by Django 3.2.2 on 2022-03-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20220324_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Количество/Обьем'),
        ),
    ]
