# Generated by Django 3.2.2 on 2022-03-24 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_offer_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='offers',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления в БД')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения в БД')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество')),
                ('offer', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='delivery.offer', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция в чеке',
                'verbose_name_plural': 'Позиции в чеке',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='delivery.CartItem', verbose_name='Товары'),
        ),
    ]
