# Generated by Django 3.2.2 on 2022-03-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20220324_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Позиция в корзине', 'verbose_name_plural': 'Позиции в корзине'},
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='delivery.cart', verbose_name='Корзина пользователя'),
        ),
    ]
