# Generated by Django 3.2.2 on 2022-03-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20220325_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='img',
            field=models.ImageField(default='', upload_to='offers', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
