# Generated by Django 3.2.2 on 2022-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Заголовок')),
                ('desc', models.CharField(max_length=64, verbose_name='Описание')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Запись в карусели',
                'verbose_name_plural': 'Записи в карусели',
            },
        ),
    ]
