# Generated by Django 3.2.2 on 2022-03-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselpost',
            name='img',
            field=models.ImageField(upload_to='carousel', verbose_name='Изображение'),
        ),
    ]
