# Generated by Django 4.0.3 on 2022-04-17 16:00

import carousel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselpost',
            name='img',
            field=models.ImageField(upload_to=carousel.models.carousel_directory_path, verbose_name='Изображение'),
        ),
    ]
